GoalSetter/config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/users')

  resources :users, only: [:new, :create, :index, :show] do
    resources :goals, only: [:new]
    resources :comments, only: [:new]
  end

  get 'leaderboard' => 'users#leaderboard'

  resources :goals, except: [:new, :show, :index] do
    resources :comments, only: [:new]
    member do
      post 'add_cheers'
    end
  end

  resource :session, only: [:new, :create, :destroy]

  resources :comments, only: [:create]

end

GoalSetter/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :commentable_id, :commentable_type, presence: true

  belongs_to :commentable, polymorphic: true

  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id,
    primary_key: :id
  )
end

GoalSetter/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable,
      class_name: "Comment",
      dependent: :destroy
  end
end

GoalSetter/app/models/goal.rb
class Goal < ActiveRecord::Base
  include Commentable
  
  validates :user_id, :objective, presence: true
  validates :privacy, :completed, inclusion: { in: [true, false] }

  belongs_to :user
end

GoalSetter/app/models/user.rb
class User < ActiveRecord::Base
  include Commentable

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :goals

  has_many(
    :authored_comments,
    class_name: 'Comment',
    foreign_key: :author_id,
    primary_key: :id
  )

  def self.user_cheers_sums
    sql = <<-SQL
      SELECT
        users.username, SUM(goals.cheers) AS cheer_sum
      FROM
        users
      LEFT OUTER JOIN
        goals
      ON
        goals.user_id = users.id
      GROUP BY
        users.username
      ORDER BY
        SUM(goals.cheers) DESC
      LIMIT
        5;
    SQL
    self.connection.execute(sql)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil if user.nil?
    return user if user.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

GoalSetter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?
  helper_method :ensure_signed_in

  def login!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
    @current_user = nil
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def ensure_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

GoalSetter/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    render :new
  end

  def create
    # @comment = Comment.new(comment_params)
    # @comment.author_id = current_user.id

    @comment = current_user.authored_comments.new(comment_params)

    if @comment.save
      if @comment.commentable_type == "User"
        redirect_to user_url(@comment.commentable)
      else
        redirect_to user_url(@comment.commentable.user)
      end
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

GoalSetter/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :ensure_signed_in

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = current_user.goals.new(goal_params)

    if @goal.save
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def update
    @goal = Goal.find(params[:id])

    raise "bad stuff" if @goal.nil?

    if @goal.update(goal_params)
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy!
    redirect_to user_url(current_user)
  end

  def add_cheers
    @goal = Goal.find(params[:id])
    user = current_user

    if user.cheers > 0
      @goal.cheers += 1
      user.cheers -= 1
      @goal.save!
      user.save!
    else
      flash[:errors] = ["You don't have any cheers left to give!"]
    end
    redirect_to user_url(@goal.user)
  end

  private

  def goal_params
    params.require(:goal).permit(:objective, :privacy, :completed)
  end
end

GoalSetter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],
                                     params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Username and/or Password was wrong"]
      @user = User.new(username: params[:user][:username])
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

GoalSetter/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_signed_in, only: [:index, :show]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def leaderboard
    @leaders = User.user_cheers_sums
    fail
    render :leaderboard
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

GoalSetter/app/helpers/application_helper.rb
module ApplicationHelper
end

GoalSetter/app/helpers/comments_helper.rb
module CommentsHelper
end

GoalSetter/app/helpers/goals_helper.rb
module GoalsHelper
end

GoalSetter/app/helpers/sessions_helper.rb
module SessionsHelper
end

GoalSetter/app/helpers/users_helper.rb
module UsersHelper
end

GoalSetter/app/views/goals/_form.html.erb
<% action_url = goal.persisted? ? goal_url(goal) : goals_url %>
<% form_method = goal.persisted? ? "patch" : "post" %>

<form action="<%= action_url %>" method="post">
  <%= token_tag form_authenticity_token %>

  <input type="hidden" name="_method" value="<%= form_method %>">

  <label>Objective
    <input type="text" name="goal[objective]" value="<%= goal.objective %>">
  </label>

  <br>

  <input type="hidden" name="goal[completed]" value="false">

  <label>Public
    <input
      type="radio"
      name="goal[privacy]"
      value="false"
      <%= "checked" unless goal.privacy %>>
  </label>

  <label>Private
    <input
      type="radio"
      name="goal[privacy]"
      value="true"
      <%= "checked" if goal.privacy %>>
  </label>

  <br>

  <input type="submit" value="Submit">

</form>

GoalSetter/app/views/goals/_goal.html.erb
<%= "COMPLETED" if goal.completed %><br>
<%= goal.objective %><br>
Cheers: <%= goal.cheers %><br>

<table>
  <tr>
    <% if current_user.id == goal.user_id %>
      <%= goal.privacy ? "Private" : "Public" %>
      <td>
        <form action="<%= edit_goal_url %>" method="get">
          <%= token_tag form_authenticity_token %>
          <input type="submit" name="Edit" value="Edit">
        </form>
      </td>

      <td>
        <form action="<%= goal_url(goal) %>" method="post">
          <%= token_tag form_authenticity_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" name="Delete" value="Delete">
        </form>
      </td>

      <td>
        <% unless goal.completed %>
          <form action="<%= goal_url(goal) %>" method="post">
            <%= token_tag form_authenticity_token %>
            <input type="hidden" name="_method" value="patch">
            <input type="hidden" name="goal[completed]" value="true">
            <input type="submit" name="Mark Complete" value="Mark Complete">
          </form>
        <% end %>
      </td>
    <% end %>
    <td>
      <form action="<%= new_goal_comment_url(goal) %>" method="get">
        <%= token_tag form_authenticity_token %>
        <input type="submit" name="Comment on Goal" value="Comment on Goal">
      </form>
    </td>
    <% unless current_user.id == goal.user_id %>
      <td>
        <form action="<%= add_cheers_goal_url(goal) %>" method="post">
          <%= token_tag form_authenticity_token %>
          <input type="submit" name="Cheers" value="Cheers">
        </form>
      </td>
    <% end %>
  </tr>
</table>

<ul>
  <% goal.comments.each do |comment| %>
    <li><%= comment.body %> by <%= comment.author.username %></li>
  <% end %>
</ul>

GoalSetter/app/views/goals/edit.html.erb
<h1>Edit This Goal</h1>

<%= render 'form', goal: @goal %>

GoalSetter/app/views/goals/new.html.erb
<h1>Create New Goal</h1>

<%= render 'form', goal: @goal %>

GoalSetter/app/views/users/index.html.erb
<h1>All Users</h1>

<a href="<%= leaderboard_url %>">To Cheer Leaderboard!</a>

<br><br>

<% @users.each do |user| %>
  <a href="<%= user_url(user) %>"><%= user.username %></a><br>
<% end %>

GoalSetter/app/views/users/new.html.erb
<h1>Create a New User</h1>

<%= render "shared/user_form", user: @user, action: :new_user %>

GoalSetter/app/views/users/show.html.erb
<a href="<%= users_url %>">To User Index</a>

<h1><%= @user.username %></h1>

<% if @user == current_user %>
  Remaining Cheers: <%= @user.cheers %>
  <br><br>
<% end %>

<form action="<%= new_user_comment_url(@user) %>" method="get">
  <%= token_tag form_authenticity_token %>
  <input type="submit" name="Comment on User" value="Comment on User">
</form>

<ul>
  <% @user.comments.each do |comment| %>
    <li><%= comment.body %> by <%= comment.author.username %></li>
  <% end %>
</ul>

<form action="<%= new_user_goal_url(@user) %>" method="get">
  <%= token_tag form_authenticity_token %>
  <input type="submit" name="Create Goal" value="Create Goal">
</form>

<br><br>

<% if current_user == @user %>
  <%= render @user.goals %>
<% else %>
  <%= render @user.goals.where(privacy: false) %>
<% end %>