MusicApp/config/routes.rb
Rails.application.routes.draw do

  resource :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:new]
  end

  resources :notes, except: [:new, :index]

  root to: redirect("/bands")

end

MusicApp/app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many(
    :notes,
    class_name: 'Note',
    foreign_key: :author_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :noted_tracks,
    through: :notes,
    source: :track
  )

  attr_reader :password

  def self.generate_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_creds(email, pw)
    user = User.find_by(email: email)

    return nil if user.nil?

    if user.is_password?(pw)
      user
    else
      nil
    end
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def reset_token!
    self.session_token = self.class.generate_token
    self.save!
    nil
  end

end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    @user.session_token = User.generate_token

    if @user.save
      login_user(@user)
      redirect_to bands_url
    else
      flash.now[:notice] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/users/new.html.erb
<h1>Sign Up!</h1>

<% if !@user.full_messages.empty? %>
  <% @user.full_messages.each do |msg| %>
    <div><%= msg %></div>
  <% end %>
<% end %>

<form action="<%= users_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Email
    <input type="text" name="user[email]" value="<%= @user.email %>">
  </label>
  <br>

  <label>Password
    <input type="text" name="user[password]">
  </label>

  <input type="submit" value="Sign Up!">
</form>

<br><br>

OR <a href="<%= new_session_url %>">Log In!</a>