99-Cats/config/routes.rb
Rails.application.routes.draw do

  resources :cats

  resources :cat_rental_requests

  post 'cat_rental_requests/:id/approve' => 'cat_rental_requests#approve', as: :req_approve
  post 'cat_rental_requests/:id/deny' => 'cat_rental_requests#deny', as: :req_deny

  resource :user, :only => [:new, :create]

  resource :session, :only => [:new, :create, :destroy]

end

99-Cats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUSES = %w(PENDING APPROVED DENIED)

  validates :cat_id, :start_date, :end_date, :user_id, :presence => true
  validates :status, :presence => true, :inclusion => { :in => STATUSES }
  
  validate :overlapping_approved_requests

  after_initialize :set_status

  belongs_to :cat

  belongs_to(
    :requester,
    :class_name => "User",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  def approve!
    self.status = "APPROVED"

    CatRentalRequest.transaction do
      self.save!
      overlapping_pending_requests.each do |req|
        req.update!(:status => "DENIED")
      end
    end

    nil
  end


  def deny!
    self.status = "DENIED"
    self.save!
  end


  def overlapping_requests
    requests = Cat.find(self.cat_id).cat_rental_requests
    requests.select do |req|
      !(self.end_date < req.start_date || req.end_date < self.start_date)
    end
  end


  def overlapping_pending_requests
    overlapping_requests.select { |req| req.status == "PENDING" }
  end


  def overlapping_approved_requests
    overlapping_requests.each do |req|
      if [self, req].all? { |el| el.status == "APPROVED"}
        errors[:base] << "That cat is busy during at least one of those days"
      end
    end

    nil
  end


  def set_status
    self.status ||= "PENDING"
  end
end

99-Cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  before_action :verify_cat_owner, only: [:approve, :deny]
  before_action :verify_request_owner, only: [:edit, :update]
  before_action :verify_logged_in, only: [:create]

  def index
    @requests = CatRentalRequest.all
    render :index
  end

  def show
    @request = CatRentalRequest.find(params[:id])
    render :show
  end

  def new
    @request = CatRentalRequest.new
    render :new
  end

  def create
    @request = CatRentalRequest.new(request_params)

    @request.user_id = current_user.id

    if @request.save
      redirect_to cat_rental_request_url(@request)
    else
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @request.update(request_params)
      redirect_to cat_rental_request_url(@request)
    else
      render :edit
    end
  end

  def approve
    @request.approve!
    redirect_to cat_url(@request.cat_id)
  end

  def deny
    @request.deny!
    redirect_to cat_url(@request.cat_id)
  end

  def destroy
  end

private

  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end

  def verify_cat_owner
    @request = CatRentalRequest.find(params[:id])

    if @request.cat.owner.id != current_user.id
      # flash some nasty message
      redirect_to cats_url
    end
  end

  def verify_request_owner
    @request = CatRentalRequest.find(params[:id])

    if @request.user_id != current_user.id
      redirect_to cats_url
    end
  end

  def verify_logged_in
    if current_user.nil?
      # flash stuff
      redirect_to new_session_url
    end
  end

end

99-Cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

99-Cats/app/views/cat_rental_requests/_form.html.erb
<% action_url = request.persisted? ? cat_rental_request_url(request) : cat_rental_requests_url %>
<% form_method = request.persisted? ? "PATCH" : "POST" %>
<% submit_text = request.persisted? ? "Update rental request!" : "Create rental request!" %>

<h2><%= request.persisted? ? "Edit #{request.id}" : "Make a new request" %></h2>

<form action="<%= action_url %>" method="post">

  <input type="hidden" name="_method" value="<%= form_method %>">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="requested_cat">Name of Cat U Want</label>
  <select name="cat_rental_request[cat_id]" id="requested_cat">

    <% Cat.all.each do |cat| %>
    <option value="<%= cat.id %>"<%= "selected" if (request.cat_id == cat.id)%> > <%= cat.name.capitalize %> </option>
    <% end %>

  </select>
  <br>

  <label for="start_date">Pick up date</label>
  <input name="cat_rental_request[start_date]" id="start_date" type="date" value="<%= request.start_date %>">

  <label for="end_date">Drop off date</label>
  <input name="cat_rental_request[end_date]" id="end_date" type="date" value="<%= request.end_date %>">

  <input type="submit" value="<%= submit_text %>">

</form>

99-Cats/app/views/cat_rental_requests/edit.html.erb
<%= render "form", request: @request %>

99-Cats/app/views/cat_rental_requests/index.html.erb
<h1>Rental Request Index!</h1>

<ul>
  <% @requests.each do |req| %>
    <li> <a href= <%= cat_rental_request_url(req) %>> <%= "#{req.id} -> #{req.cat.name}" %> </a>
  <% end %>
</ul>

99-Cats/app/views/cat_rental_requests/new.html.erb
<%= render "form", request: @request %>

99-Cats/app/views/cat_rental_requests/show.html.erb
<h1>Request Number <%= @request.id %> Show Page</h1>

<table>
  <% @request.attributes.each do |k,v| %>
    <% next if ["created_at", "updated_at"].include?(k) %>
    <tr>
      <% if k == "cat_id" %>
        <td><u>Name</u></td><td><%= @request.cat.name %></td>
      <% else %>
        <td><u><%= k %></u></td><td><%= v %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<br><br><br>
<a href= <%= cat_rental_requests_url %>>Index</a>
<br><br>
<a href= <%= edit_cat_rental_request_url %>>Edit Rental Request</a>