MusicApp/config/routes.rb
Rails.application.routes.draw do

  resource :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:new]
  end

  resources :notes, except: [:new, :index]

  root to: redirect("/bands")

end

MusicApp/app/models/track.rb
class Track < ActiveRecord::Base

  KINDS = %w( Bonus Regular )

  validates :album_id, :name, :kind, :lyrics, presence: true
  validates :kind, inclusion: { in: KINDS }

  belongs_to :album

  has_many :notes, dependent: :destroy
  
end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :ensure_logged_in

  def new
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:notice] = @track.errors.full_messages
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:notice] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    album_id = @track.album_id
    @track.destroy!
    redirect_to album_url(album_id)
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id, :kind, :lyrics)
  end

  def ensure_logged_in
    if current_user.nil?
      flash[:notice] = "Must be logged-in!"
      redirect_to new_session_url
    end
  end

end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper

  def ugly_lyrics(lyrics)
    h(lyrics.split("\n").map { |l| "♫" + l }.join).html_safe
  end

end

MusicApp/app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% form_method = track.persisted? ? "PATCH" : "POST" %>
<% submit_text = track.persisted? ? "Update Track!" : "Create Track!" %>

<% if !track.full_messages.empty? %>
  <% track.full_messages.each do |msg| %>
    <div><%= msg %></div>
  <% end %>
<% end %>

<form action="<%= action_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="<%= form_method %>">

  <label>Name
    <input type="text" name="track[name]" value="<%= track.name %>">
  </label>

  <br><br>

  <label>Album
    <select name="track[album_id]">
      <% Album.all.each do |album| %>
        <option
          value="<%= album.id %>"
          <%= "selected" if album.id == track.album_id %>>
          <%= album.name %>
        </option>
      <% end %>
    </select>
  </label>

  <br><br>

  <div>
    <% Track::KINDS.each do |kind| %>
      <% label = "track_kind_#{kind}" %>
      <label for="<%= label %>">
      <input
        id="<%= label %>"
        name="track[kind]"
        type="radio"
        value="<%= kind %>"
        <%= "checked" if track.kind == kind %>>
        <%= kind %>
      </input>
    <% end %>
  </div>

  <br>

  <label>Lyrics
    <textarea name="track[lyrics]"><%= track.lyrics %></textarea>
  </label>

  <br>

  <input type="submit" value="<%= submit_text %>">
</form>

MusicApp/app/views/tracks/edit.html.erb
<h1>Edit track.</h1>

<%= render "form", track: @track %>

MusicApp/app/views/tracks/new.html.erb
<h1>Create a new track.</h1>

<%= render "form", track: @track %>

MusicApp/app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
from <a href="<%= album_url(@track.album_id)%>"><%= @track.album.name %></a>

<br><br>

<a href="<%= edit_track_url(@track)%>">Edit.</a>

<br><br>

<form action="<%= track_url(@track) %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="DELETE!">
</form>

<br><br>

Kind = <%= @track.kind %>

<br><br>

<u>Lyrics:</u>

<pre><%= ugly_lyrics(@track.lyrics) %></pre>

<a href="<%= new_track_note_url(@track) %>">Create new note!</a>

<br><br>

<u>Notes:</u>

<br><br>

<%= render @track.notes %>